controller_list:
  - name: fake_mrm_arm_controller
    type: $(arg execution_type)
    joints:
      - base_link__link_01
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - link_04__link_05
initial:  # Define initial robot poses.
  - group: mrm_arm
    pose: home